version: "3"

services:
  database:
    container_name: simulacion
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: simulacion
    ports:
      - 5000:5432
    volumes:
      - ./data:/var/lib/postgresql/data
